### ISSUE TITLE
Asynchronous Chunk loading fails

### ISSUE THREAD

**Issue by Lioncat6** [Euphillya/WorldGuard-Folia#5]
Whenever attempting an edit which requires the plugin to load an area, this error message is received: 
![image](https://github.com/user-attachments/assets/ed88e09d-c836-41dd-bcf7-377fc6f5fb96)

```[18:44:13 ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread Region Scheduler Thread #0 failed main thread check: Cannot asynchronously load chunks
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:51) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.level.ServerChunkCache.syncLoad(ServerChunkCache.java:100) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.level.ServerChunkCache.getChunkFallback(ServerChunkCache.java:153) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:296) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.world.level.Level.getChunk(Level.java:1095) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.world.level.Level.getBlockState(Level.java:1396) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21_4.PaperweightWorldNativeAccess.fireNeighborChanged(PaperweightWorldNativeAccess.java:164) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21_4.PaperweightWorldNativeAccess.notifyNeighbors(PaperweightWorldNativeAccess.java:146) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21_4.PaperweightWorldNativeAccess.notifyNeighbors(PaperweightWorldNativeAccess.java:45) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.internal.wna.WorldNativeAccess.markAndNotifyBlock(WorldNativeAccess.java:186) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.internal.wna.WorldNativeAccess.applySideEffects(WorldNativeAccess.java:110) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.BukkitWorld.applySideEffects(BukkitWorld.java:518) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.world.SideEffectExtent$1.resume(SideEffectExtent.java:132) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:91) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:984) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.EditSession.close(EditSession.java:928) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:515) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:391) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2356) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2330) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2502) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1795) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.2.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[18:44:13 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: Cannot asynchronously load chunks
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:52) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.level.ServerChunkCache.syncLoad(ServerChunkCache.java:100) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.level.ServerChunkCache.getChunkFallback(ServerChunkCache.java:153) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:296) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.world.level.Level.getChunk(Level.java:1095) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.world.level.Level.getBlockState(Level.java:1396) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21_4.PaperweightWorldNativeAccess.fireNeighborChanged(PaperweightWorldNativeAccess.java:164) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21_4.PaperweightWorldNativeAccess.notifyNeighbors(PaperweightWorldNativeAccess.java:146) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21_4.PaperweightWorldNativeAccess.notifyNeighbors(PaperweightWorldNativeAccess.java:45) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.internal.wna.WorldNativeAccess.markAndNotifyBlock(WorldNativeAccess.java:186) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.internal.wna.WorldNativeAccess.applySideEffects(WorldNativeAccess.java:110) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.BukkitWorld.applySideEffects(BukkitWorld.java:518) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.world.SideEffectExtent$1.resume(SideEffectExtent.java:132) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:91) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:984) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.EditSession.close(EditSession.java:928) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:515) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:391) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2356) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2330) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2502) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1795) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.2.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]```

**Comment by Lioncat6** [comment]
wrong repo lol
